import asyncio
import json
import logging
import os
import re
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Set, Tuple

import aiofiles

logger = logging.getLogger(__name__)


class RelationshipService:
    def __init__(self, llm_service, data_dir: str):
        self.llm_service = llm_service
        self.data_dir = data_dir

        # Tạo thư mục relationships
        self.relationships_dir = os.path.join(data_dir, "relationships")
        os.makedirs(self.relationships_dir, exist_ok=True)

        # Files để lưu data
        self.relationships_file = os.path.join(
            self.relationships_dir, "relationships.json"
        )
        self.user_names_file = os.path.join(self.relationships_dir, "user_names.json")
        self.interactions_file = os.path.join(
            self.relationships_dir, "interactions.json"
        )
        self.conversation_history_file = os.path.join(
            self.relationships_dir, "conversation_history.json"
        )

        # Load existing data
        self.relationships = self._load_relationships()
        self.user_names = self._load_user_names()
        self.interactions = self._load_interactions()
        self.conversation_history = self._load_conversation_history()

        logger.info(
            f"🔗 RelationshipService initialized with {len(self.relationships)} relationships"
        )

    async def update_server_relationships_summary(self):
        """Auto-generate and update server_relationships.txt with AI-generated summary"""
        summary_data = self.get_all_users_summary()
        prompt = self._build_server_relationships_prompt(summary_data)
        try:
            ai_summary = await self.llm_service.generate_response(
                prompt, "server_summary"
            )
        except Exception as e:
            logger.error(f"Error generating server relationships summary: {e}")
            ai_summary = "Không thể tạo tổng kết mối quan hệ server lúc này."
        # Write to file
        server_summary_path = os.path.join(self.data_dir, "server_relationships.txt")
        async with aiofiles.open(server_summary_path, mode="w", encoding="utf-8") as f:
            await f.write(
                "# server_relationships.txt\n# This file is auto-generated by the bot. Do not edit manually.\n\n"
            )
            await f.write(ai_summary)

    def _build_server_relationships_prompt(self, summary_data: dict) -> str:
        """Build prompt for AI to summarize all server relationships"""
        prompt = """Tổng hợp và phân tích các mối quan hệ trong server Discord dựa trên dữ liệu sau. Hãy chỉ sử dụng user_id để tránh nhầm lẫn tên. Trả lời bằng tiếng Việt, ngắn gọn, dễ hiểu, có thể chia thành các mục:

"""
        prompt += f"TỔNG NGƯỜI DÙNG: {summary_data['total_users']}\nTỔNG MỐI QUAN HỆ: {summary_data['total_relationships']}\nTỔNG TƯƠNG TÁC: {summary_data['total_interactions']}\n\n"
        for user in summary_data["users"]:
            prompt += f"- User ID: {user['user_id']}: {user['relationship_count']} mối quan hệ, {user['interaction_stats'].get('total_interactions', 0)} tương tác\n"
        prompt += "\nDỮ LIỆU CHI TIẾT:\n"
        for user in summary_data["users"]:
            prompt += f"\n=== User ID: {user['user_id']} ===\n"
            prompt += f"Tên thật: {user.get('real_name', '')}\n"
            prompt += f"Số mối quan hệ: {user['relationship_count']}\n"
            prompt += f"Tổng tương tác: {user['interaction_stats'].get('total_interactions', 0)}\n"
            if user["interaction_stats"].get("top_contacts"):
                prompt += "Liên lạc thường xuyên: "
                prompt += (
                    ", ".join(
                        [
                            f"User ID: {c['user_id']} ({c['interaction_count']})"
                            for c in user["interaction_stats"]["top_contacts"]
                        ]
                    )
                    + "\n"
                )
        prompt += "\nHãy phân tích, nhận xét tổng quan về các nhóm/tương tác nổi bật, network xã hội, và đưa ra nhận định về từng người nếu có đủ dữ liệu.\nChỉ dùng user_id, không dùng tên hiển thị."
        return prompt

    async def auto_update_server_summary_on_change(self):
        """Call this after any relationship/interactions update to keep server_relationships.txt fresh."""
        await self.update_server_relationships_summary()

    def _load_relationships(self) -> Dict:
        """Load relationship data from file"""
        if not os.path.exists(self.relationships_file):
            return {}

        try:
            with open(self.relationships_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading relationships: {e}")
            return {}

    def _save_relationships(self):
        """Save relationship data to file"""
        try:
            with open(self.relationships_file, "w", encoding="utf-8") as f:
                json.dump(self.relationships, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving relationships: {e}")
        # Trigger server summary update (fire and forget)
        try:
            import asyncio

            if asyncio.get_event_loop().is_running():
                asyncio.create_task(self.auto_update_server_summary_on_change())
        except Exception as e:
            logger.error(f"Error scheduling server summary update: {e}")

    def _load_user_names(self) -> Dict:
        """Load user names mapping from file"""
        if not os.path.exists(self.user_names_file):
            return {}

        try:
            with open(self.user_names_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading user names: {e}")
            return {}

    def _save_user_names(self):
        """Save user names mapping to file"""
        try:
            with open(self.user_names_file, "w", encoding="utf-8") as f:
                json.dump(self.user_names, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving user names: {e}")

    def _load_interactions(self) -> Dict:
        """Load interaction data from file"""
        if not os.path.exists(self.interactions_file):
            return {}

        try:
            with open(self.interactions_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading interactions: {e}")
            return {}

    def _save_interactions(self):
        """Save interaction data to file"""
        try:
            with open(self.interactions_file, "w", encoding="utf-8") as f:
                json.dump(self.interactions, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving interactions: {e}")
        # Trigger server summary update (fire and forget)
        try:
            import asyncio

            if asyncio.get_event_loop().is_running():
                asyncio.create_task(self.auto_update_server_summary_on_change())
        except Exception as e:
            logger.error(f"Error scheduling server summary update: {e}")

    def _load_conversation_history(self) -> Dict:
        """Load conversation history between users"""
        if not os.path.exists(self.conversation_history_file):
            return {}

        try:
            with open(self.conversation_history_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading conversation history: {e}")
            return {}

    def _save_conversation_history(self):
        """Save conversation history"""
        try:
            with open(self.conversation_history_file, "w", encoding="utf-8") as f:
                json.dump(self.conversation_history, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving conversation history: {e}")
        # Trigger server summary update (fire and forget)
        try:
            import asyncio

            if asyncio.get_event_loop().is_running():
                asyncio.create_task(self.auto_update_server_summary_on_change())
        except Exception as e:
            logger.error(f"Error scheduling server summary update: {e}")

    def update_user_name(
        self,
        user_id: str,
        username: str,
        display_name: Optional[str] = None,
        real_name: Optional[str] = None,
    ):
        """Update user name information"""
        if user_id not in self.user_names:
            self.user_names[user_id] = {
                "username": username,
                "display_name": display_name,
                "real_name": real_name,
                "name_history": [username],
                "first_seen": datetime.now().isoformat(),
                "last_updated": datetime.now().isoformat(),
            }
        else:
            # Update existing info
            self.user_names[user_id]["username"] = username
            if display_name:
                self.user_names[user_id]["display_name"] = display_name
            if real_name and real_name != self.user_names[user_id].get("real_name"):
                self.user_names[user_id]["real_name"] = real_name
                logger.info(f"📝 Real name updated for {user_id}: {real_name}")

            # Track name history
            if username not in self.user_names[user_id]["name_history"]:
                self.user_names[user_id]["name_history"].append(username)

            self.user_names[user_id]["last_updated"] = datetime.now().isoformat()

        self._save_user_names()

    def get_user_display_name(self, user_id: str) -> str:
        """Get the best display name for a user (real name > display name > username)"""
        # Handle None case
        if user_id is None:
            return "Unknown User"

        if user_id not in self.user_names:
            return f"User_{user_id[-4:]}"  # Fallback với 4 số cuối của ID

        user_info = self.user_names[user_id]

        # Ưu tiên: tên thật > display name > username
        if user_info.get("real_name"):
            return user_info["real_name"]
        elif user_info.get("display_name"):
            return user_info["display_name"]
        else:
            return user_info["username"]

    def extract_mentioned_users(self, message_content: str) -> List[str]:
        """Extract mentioned user IDs from message content"""
        # Discord mention pattern: <@!123456789> or <@123456789>
        mention_pattern = r"<@!?(\d+)>"
        mentions = re.findall(mention_pattern, message_content)
        return mentions

    async def extract_relationship_info(
        self, message_content: str, author_id: str
    ) -> List[Dict]:
        """Extract relationship information from message content using LLM"""
        try:
            # Create a prompt for the LLM to analyze relationships in the message
            prompt = f"""Phân tích tin nhắn sau để xác định các mối quan hệ giữa người dùng:

TIN NHẮN: {message_content}

Hãy xác định các cặp người dùng và mối quan hệ giữa họ. Trả lời theo định dạng JSON như sau:
{{
  "relationships": [
    {{
      "person1": "tên người 1",
      "person2": "tên người 2", 
      "relationship_type": "friend|crush|dislike|romantic|dating|ex|unknown",
      "confidence": 0.0-1.0,
      "context": "ngữ cảnh xác định mối quan hệ"
    }}
  ]
}}

Chỉ trả lời dưới dạng JSON, không giải thích thêm:"""

            # Call the LLM to analyze relationships
            llm_response = await self.llm_service.generate_response(
                prompt, "relationship_extraction"
            )

            # Parse the LLM response as JSON
            import json

            # First, try to parse the entire response as JSON
            try:
                response_json = json.loads(llm_response)
            except json.JSONDecodeError:
                # If that fails, try to extract JSON from the response
                # Look for JSON between curly braces
                import re

                json_match = re.search(r"\{.*\}", llm_response, re.DOTALL)
                if json_match:
                    json_str = json_match.group()
                    response_json = json.loads(json_str)
                else:
                    # If still no JSON found, raise the original exception
                    raise json.JSONDecodeError(
                        "No JSON found in response", llm_response, 0
                    )

            relationships_found = []
            for rel_data in response_json.get("relationships", []):
                # Validate that required fields exist
                if (
                    "person1" in rel_data
                    and "person2" in rel_data
                    and "relationship_type" in rel_data
                ):
                    relationships_found.append(
                        {
                            "person1": rel_data["person1"].strip(),
                            "person2": rel_data["person2"].strip(),
                            "relationship_type": rel_data["relationship_type"],
                            "reported_by": author_id,
                            "timestamp": datetime.now().isoformat(),
                            "context": rel_data.get("context", ""),
                            "confidence": rel_data.get(
                                "confidence", 0.7
                            ),  # Default confidence if not provided
                        }
                    )

            return relationships_found

        except json.JSONDecodeError:
            logger.error(
                "Failed to parse LLM response as JSON in extract_relationship_info"
            )
            # Fallback to simple regex if LLM fails
            return self._extract_relationship_info_fallback(message_content, author_id)
        except Exception as e:
            logger.error(f"Error extracting relationship info with LLM: {e}")
            # Fallback to simple regex if LLM fails
            return self._extract_relationship_info_fallback(message_content, author_id)

    def _extract_relationship_info_fallback(
        self, message_content: str, author_id: str
    ) -> List[Dict]:
        """Fallback method using regex patterns if LLM fails"""
        relationships_found = []
        content_lower = message_content.lower()

        # Patterns để detect relationship statements
        relationship_patterns = [
            # X và Y là bạn
            r"(\w+)\s+(?:và|với)\s+(\w+)\s+(?:là|are)\s+(?:bạn|friends?|buddies?)",
            # X bạn với Y
            r"(\w+)\s+(?:bạn|friend)\s+(?:với|with)\s+(\w+)",
            # X và Y quen nhau
            r"(\w+)\s+(?:và|với)\s+(\w+)\s+(?:quen\s+nhau|know\s+each\s+other)",
            # X thích Y
            r"(\w+)\s+(?:thích|likes?|has\s+a\s+crush\s+on)\s+(\w+)",
            # X ghét Y
            r"(\w+)\s+(?:ghét|hates?|dislikes?)\s+(\w+)",
            # X là người yêu của Y
            r"(\w+)\s+(?:là\s+)?(?:người\s+yêu|boyfriend|girlfriend|partner)\s+(?:của\s+)?(\w+)",
            # X đang hẹn hò với Y
            r"(\w+)\s+(?:đang\s+)?(?:hẹn\s+hò|dating)\s+(?:với\s+)?(\w+)",
            # X chia tay với Y
            r"(\w+)\s+(?:chia\s+tay|broke\s+up)\s+(?:với\s+)?(\w+)",
        ]

        for pattern in relationship_patterns:
            matches = re.finditer(pattern, content_lower)
            for match in matches:
                person1, person2 = match.groups()

                # Determine relationship type based on pattern
                relationship_type = "unknown"
                if "bạn" in match.group() or "friend" in match.group():
                    relationship_type = "friend"
                elif (
                    "thích" in match.group()
                    or "likes" in match.group()
                    or "crush" in match.group()
                ):
                    relationship_type = "crush"
                elif "ghét" in match.group() or "hate" in match.group():
                    relationship_type = "dislike"
                elif (
                    "người yêu" in match.group()
                    or "boyfriend" in match.group()
                    or "girlfriend" in match.group()
                ):
                    relationship_type = "romantic"
                elif "hẹn hò" in match.group() or "dating" in match.group():
                    relationship_type = "dating"
                elif "chia tay" in match.group() or "broke up" in match.group():
                    relationship_type = "ex"

                relationships_found.append(
                    {
                        "person1": person1.strip(),
                        "person2": person2.strip(),
                        "relationship_type": relationship_type,
                        "reported_by": author_id,
                        "timestamp": datetime.now().isoformat(),
                        "context": match.group(),
                        "confidence": 0.5,  # Lower confidence for regex-based detection
                    }
                )

        return relationships_found

    async def process_message(
        self,
        author_id: str,
        author_username: str,
        message_content: str,
        mentioned_user_ids: Optional[List[str]] = None,
        channel_id: Optional[str] = None,
    ):
        """Process a message to extract and update relationship information"""

        # Update author's name info
        self.update_user_name(author_id, author_username)

        # Extract mentions from message if not provided
        if mentioned_user_ids is None:
            mentioned_user_ids = self.extract_mentioned_users(message_content)

        # Record mentions/interactions
        if mentioned_user_ids:
            self._record_interactions(
                author_id, mentioned_user_ids, "mention", message_content
            )

        # Extract relationship info from message content
        relationships_found = await self.extract_relationship_info(
            message_content, author_id
        )

        # Process found relationships
        for rel_info in relationships_found:
            self._add_relationship(
                rel_info["person1"],
                rel_info["person2"],
                rel_info["relationship_type"],
                rel_info["reported_by"],
                rel_info["context"],
                rel_info["confidence"],
            )

        # Record conversation for history
        self._record_conversation(
            author_id, message_content, mentioned_user_ids, channel_id
        )

        logger.debug(
            f"🔗 Processed message from {author_username}: {len(relationships_found)} relationships, {len(mentioned_user_ids)} mentions"
        )

    def _record_interactions(
        self,
        author_id: str,
        target_user_ids: List[str],
        interaction_type: str,
        context: str = "",
    ):
        """Record interactions between users"""
        timestamp = datetime.now().isoformat()

        for target_id in target_user_ids:
            # Create interaction key
            interaction_key = f"{author_id}_{target_id}"

            if interaction_key not in self.interactions:
                self.interactions[interaction_key] = {
                    "from_user": author_id,
                    "to_user": target_id,
                    "interactions": [],
                }

            # Add interaction
            self.interactions[interaction_key]["interactions"].append(
                {
                    "type": interaction_type,
                    "timestamp": timestamp,
                    "context": context[:200],  # Limit context length
                }
            )

            # Keep only recent interactions (last 100)
            if len(self.interactions[interaction_key]["interactions"]) > 100:
                self.interactions[interaction_key]["interactions"] = self.interactions[
                    interaction_key
                ]["interactions"][-100:]

        self._save_interactions()

    def _record_conversation(
        self,
        author_id: str,
        message_content: str,
        mentioned_users: List[str],
        channel_id: Optional[str],
    ):
        """Record conversation history between users"""
        timestamp = datetime.now().isoformat()

        # Record conversation entry
        conversation_entry = {
            "author_id": author_id,
            "message": message_content[:500],  # Limit message length
            "mentioned_users": mentioned_users,
            "channel_id": channel_id,
            "timestamp": timestamp,
        }

        # Group conversations by participants
        participants = sorted([author_id] + mentioned_users)
        conversation_key = "_".join(participants)

        if conversation_key not in self.conversation_history:
            self.conversation_history[conversation_key] = {
                "participants": participants,
                "messages": [],
            }

        self.conversation_history[conversation_key]["messages"].append(
            conversation_entry
        )

        # Keep only recent messages (last 50 per conversation)
        if len(self.conversation_history[conversation_key]["messages"]) > 50:
            self.conversation_history[conversation_key]["messages"] = (
                self.conversation_history[conversation_key]["messages"][-50:]
            )

        self._save_conversation_history()

    def _add_relationship(
        self,
        person1: str,
        person2: str,
        relationship_type: str,
        reported_by: str,
        context: str,
        confidence: float,
    ):
        """Add or update a relationship"""
        # Normalize names and create a consistent key
        person1_lower = person1.lower().strip()
        person2_lower = person2.lower().strip()

        # Create sorted key to avoid duplicates (A->B vs B->A)
        if person1_lower < person2_lower:
            rel_key = f"{person1_lower}_{person2_lower}"
            persons = (person1, person2)
        else:
            rel_key = f"{person2_lower}_{person1_lower}"
            persons = (person2, person1)

        timestamp = datetime.now().isoformat()

        if rel_key not in self.relationships:
            self.relationships[rel_key] = {
                "person1": persons[0],
                "person2": persons[1],
                "relationship_history": [],
            }

        # Add relationship entry
        relationship_entry = {
            "type": relationship_type,
            "reported_by": reported_by,
            "context": context,
            "confidence": confidence,
            "timestamp": timestamp,
        }

        self.relationships[rel_key]["relationship_history"].append(relationship_entry)

        # Keep only recent relationship updates (last 20)
        if len(self.relationships[rel_key]["relationship_history"]) > 20:
            self.relationships[rel_key]["relationship_history"] = self.relationships[
                rel_key
            ]["relationship_history"][-20:]

        self._save_relationships()

        logger.info(
            f"🔗 Added relationship: {person1} - {person2} ({relationship_type}) reported by {reported_by}"
        )

    def get_user_relationships(self, user_identifier: str) -> List[Dict]:
        """Get all relationships for a user (by ID, username, or real name)"""
        relationships = []

        # Find user ID from identifier
        user_id = self._resolve_user_identifier(user_identifier)
        if not user_id:
            return relationships

        user_display_name = self.get_user_display_name(user_id).lower()

        for rel_key, rel_data in self.relationships.items():
            person1 = rel_data["person1"].lower()
            person2 = rel_data["person2"].lower()

            if user_display_name == person1 or user_display_name == person2:
                # Get the latest relationship status
                if rel_data["relationship_history"]:
                    latest_rel = rel_data["relationship_history"][-1]
                    other_person = (
                        rel_data["person2"]
                        if user_display_name == person1
                        else rel_data["person1"]
                    )

                    relationships.append(
                        {
                            "other_person": other_person,
                            "relationship_type": latest_rel["type"],
                            "reported_by": latest_rel["reported_by"],
                            "context": latest_rel["context"],
                            "timestamp": latest_rel["timestamp"],
                            "confidence": latest_rel["confidence"],
                        }
                    )

        return relationships

    def get_interaction_stats(self, user_identifier: str) -> Dict:
        """Get interaction statistics for a user"""
        user_id = self._resolve_user_identifier(user_identifier)
        if not user_id:
            return {}

        # Count mentions and interactions
        mentions_sent = 0
        mentions_received = 0
        frequent_contacts = Counter()

        for interaction_key, interaction_data in self.interactions.items():
            if interaction_data["from_user"] == user_id:
                mentions_sent += len(interaction_data["interactions"])
                frequent_contacts[interaction_data["to_user"]] += len(
                    interaction_data["interactions"]
                )
            elif interaction_data["to_user"] == user_id:
                mentions_received += len(interaction_data["interactions"])

        # Get top contacts
        top_contacts = []
        for contact_id, count in frequent_contacts.most_common(5):
            contact_name = self.get_user_display_name(contact_id)
            top_contacts.append(
                {
                    "name": contact_name,
                    "user_id": contact_id,
                    "interaction_count": count,
                }
            )

        return {
            "mentions_sent": mentions_sent,
            "mentions_received": mentions_received,
            "total_interactions": mentions_sent + mentions_received,
            "top_contacts": top_contacts,
        }

    def get_conversation_summary(
        self, user1_identifier: str, user2_identifier: str, days_back: int = 7
    ) -> str:
        """Get conversation summary between two users"""
        user1_id = self._resolve_user_identifier(user1_identifier)
        user2_id = self._resolve_user_identifier(user2_identifier)

        if not user1_id or not user2_id:
            return "Không tìm thấy thông tin người dùng."

        # Find conversation between these users
        participants = sorted([user1_id, user2_id])
        conversation_key = "_".join(participants)

        if conversation_key not in self.conversation_history:
            return f"Không có lịch sử trò chuyện giữa {self.get_user_display_name(user1_id)} và {self.get_user_display_name(user2_id)}."

        # Filter messages from the last N days
        cutoff_date = datetime.now() - timedelta(days=days_back)
        recent_messages = []

        for msg in self.conversation_history[conversation_key]["messages"]:
            msg_date = datetime.fromisoformat(msg["timestamp"])
            if msg_date >= cutoff_date:
                recent_messages.append(msg)

        if not recent_messages:
            return f"Không có cuộc trò chuyện nào trong {days_back} ngày qua giữa {self.get_user_display_name(user1_id)} và {self.get_user_display_name(user2_id)}."

        # Format conversation for summary
        conversation_text = ""
        for msg in recent_messages[-10:]:  # Last 10 messages
            author_name = self.get_user_display_name(msg["author_id"])
            conversation_text += f"{author_name}: {msg['message']}\n"

        return f"Cuộc trò chuyện gần đây giữa {self.get_user_display_name(user1_id)} và {self.get_user_display_name(user2_id)}:\n\n{conversation_text}"

    async def generate_relationship_analysis(self, user_identifier: str) -> str:
        """Generate AI analysis of user's relationships"""
        user_id = self._resolve_user_identifier(user_identifier)
        if not user_id:
            return "Không tìm thấy thông tin người dùng."

        user_name = self.get_user_display_name(user_id)
        relationships = self.get_user_relationships(user_identifier)
        interaction_stats = self.get_interaction_stats(user_identifier)

        if not relationships and not interaction_stats.get("total_interactions", 0):
            return f"Chưa có thông tin về mối quan hệ của {user_name}."

        # Prepare data for AI analysis
        analysis_prompt = f"""Phân tích mối quan hệ của {user_name} dựa trên thông tin sau:

THÔNG TIN NGƯỜI DÙNG: {user_name} (ID: {user_id})

CÁC MỐI QUAN HỆ:
"""

        for rel in relationships:
            analysis_prompt += f"- {rel['other_person']}: {rel['relationship_type']} (độ tin cậy: {rel['confidence']}, được báo cáo bởi: {self.get_user_display_name(rel['reported_by'])})\n"

        analysis_prompt += f"""
THỐNG KÊ TƯƠNG TÁC:
- Mentions gửi đi: {interaction_stats.get("mentions_sent", 0)}
- Mentions nhận được: {interaction_stats.get("mentions_received", 0)}
- Tổng tương tác: {interaction_stats.get("total_interactions", 0)}

NGƯỜI LIÊN LẠC THƯỜNG XUYÊN:
"""

        for contact in interaction_stats.get("top_contacts", []):
            analysis_prompt += (
                f"- {contact['name']}: {contact['interaction_count']} lần tương tác\n"
            )

        analysis_prompt += """
Hãy phân tích và đưa ra nhận xét về:
1. Tính cách xã hội của người này
2. Mối quan hệ chính và tần suất tương tác
3. Đánh giá tổng quan về network xã hội
4. Gợi ý về cách cải thiện mối quan hệ (nếu có)

Trả lời bằng tiếng Việt, ngắn gọn và dễ hiểu:"""

        try:
            analysis = await self.llm_service.generate_response(
                analysis_prompt, user_id
            )
            return f"📊 **Phân tích mối quan hệ của {user_name}:**\n\n{analysis}"
        except Exception as e:
            logger.error(f"Error generating relationship analysis: {e}")
            return f"Không thể tạo phân tích cho {user_name} lúc này."

    def _resolve_user_identifier(self, identifier: str) -> Optional[str]:
        """Resolve user identifier (ID, username, or real name) to user ID"""
        # Handle None case
        if identifier is None:
            return None

        # Handle mention format <@ID> or <@!ID>
        if identifier.startswith("<@") and identifier.endswith(">"):
            # Extract user ID from mention
            user_id = identifier[2:-1]  # Remove <@ and >
            if user_id.startswith("!"):
                user_id = user_id[1:]  # Remove ! if present (<@!ID>)
            # Check if this ID exists in our records
            if user_id in self.user_names:
                return user_id
            # If not in our records, return the extracted ID anyway
            return user_id

        # Direct ID match
        if identifier in self.user_names:
            return identifier

        # Search by username or real name
        identifier_lower = identifier.lower().strip()

        for user_id, user_info in self.user_names.items():
            # Check username
            if user_info.get("username", "").lower() == identifier_lower:
                return user_id

            # Check display name
            if user_info.get("display_name", "").lower() == identifier_lower:
                return user_id

            # Check real name
            if user_info.get("real_name", "").lower() == identifier_lower:
                return user_id

            # Check name history
            for name in user_info.get("name_history", []):
                if name.lower() == identifier_lower:
                    return user_id

        return None

    def search_relationships_by_keyword(self, keyword: str) -> List[Dict]:
        """Search relationships by keyword in context"""
        results = []
        keyword_lower = keyword.lower()

        for rel_key, rel_data in self.relationships.items():
            for rel_entry in rel_data["relationship_history"]:
                if keyword_lower in rel_entry["context"].lower():
                    results.append(
                        {
                            "person1": rel_data["person1"],
                            "person2": rel_data["person2"],
                            "relationship_type": rel_entry["type"],
                            "context": rel_entry["context"],
                            "timestamp": rel_entry["timestamp"],
                            "reported_by": self.get_user_display_name(
                                rel_entry["reported_by"]
                            ),
                        }
                    )

        # Sort by timestamp (newest first)
        results.sort(key=lambda x: x["timestamp"], reverse=True)
        return results[:10]  # Return top 10 results

    def get_user_mentions_to(
        self, user_identifier: str, target_identifier: str
    ) -> List[Dict]:
        """Get mentions from one user to another"""
        user_id = self._resolve_user_identifier(user_identifier)
        target_id = self._resolve_user_identifier(target_identifier)

        if not user_id or not target_id:
            return []

        interaction_key = f"{user_id}_{target_id}"

        if interaction_key in self.interactions:
            return self.interactions[interaction_key]["interactions"]

        return []

    def get_all_users_summary(self) -> Dict:
        """Get summary of all tracked users"""
        summary = {
            "total_users": len(self.user_names),
            "total_relationships": len(self.relationships),
            "total_interactions": sum(
                len(data["interactions"]) for data in self.interactions.values()
            ),
            "users": [],
        }

        for user_id, user_info in self.user_names.items():
            user_summary = {
                "user_id": user_id,
                "display_name": self.get_user_display_name(user_id),
                "username": user_info.get("username", ""),
                "real_name": user_info.get("real_name", ""),
                "first_seen": user_info.get("first_seen", ""),
                "relationship_count": len(self.get_user_relationships(user_id)),
                "interaction_stats": self.get_interaction_stats(user_id),
            }
            summary["users"].append(user_summary)

        # Sort users by total interactions
        summary["users"].sort(
            key=lambda x: x["interaction_stats"].get("total_interactions", 0),
            reverse=True,
        )

        return summary
