import json
import logging
import os
from datetime import datetime
from typing import Dict, Optional

import aiofiles

logger = logging.getLogger(__name__)


class RelationshipStorage:
    def __init__(self, data_dir: str):
        self.data_dir = data_dir

        # Tạo thư mục relationships
        self.relationships_dir = os.path.join(data_dir, "relationships")
        os.makedirs(self.relationships_dir, exist_ok=True)

        # Files để lưu data
        self.relationships_file = os.path.join(
            self.relationships_dir, "relationships.json"
        )
        self.user_names_file = os.path.join(self.relationships_dir, "user_names.json")
        self.interactions_file = os.path.join(
            self.relationships_dir, "interactions.json"
        )
        self.conversation_history_file = os.path.join(
            self.relationships_dir, "conversation_history.json"
        )

    def _load_relationships(self) -> Dict:
        """Load relationship data from file"""
        if not os.path.exists(self.relationships_file):
            return {}

        try:
            with open(self.relationships_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading relationships: {e}")
            return {}

    def _save_relationships(self, relationships: Dict):
        """Save relationship data to file"""
        try:
            with open(self.relationships_file, "w", encoding="utf-8") as f:
                json.dump(relationships, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving relationships: {e}")

    def _load_user_names(self) -> Dict:
        """Load user names mapping from file"""
        if not os.path.exists(self.user_names_file):
            return {}

        try:
            with open(self.user_names_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading user names: {e}")
            return {}

    def _save_user_names(self, user_names: Dict):
        """Save user names mapping to file"""
        try:
            with open(self.user_names_file, "w", encoding="utf-8") as f:
                json.dump(user_names, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving user names: {e}")

    def _load_interactions(self) -> Dict:
        """Load interaction data from file"""
        if not os.path.exists(self.interactions_file):
            return {}

        try:
            with open(self.interactions_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading interactions: {e}")
            return {}

    def _save_interactions(self, interactions: Dict):
        """Save interaction data to file"""
        try:
            with open(self.interactions_file, "w", encoding="utf-8") as f:
                json.dump(interactions, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving interactions: {e}")

    def _load_conversation_history(self) -> Dict:
        """Load conversation history between users"""
        if not os.path.exists(self.conversation_history_file):
            return {}

        try:
            with open(self.conversation_history_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading conversation history: {e}")
            return {}

    def _save_conversation_history(self, conversation_history: Dict):
        """Save conversation history"""
        try:
            with open(self.conversation_history_file, "w", encoding="utf-8") as f:
                json.dump(conversation_history, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Error saving conversation history: {e}")

    async def update_server_relationships_summary(
        self, llm_service, summary_data: dict
    ):
        """Auto-generate and update server_relationships.txt with AI-generated summary"""
        prompt = self._build_server_relationships_prompt(summary_data)
        try:
            ai_summary = await llm_service.generate_response(prompt, "server_summary")
        except Exception as e:
            logger.error(f"Error generating server relationships summary: {e}")
            ai_summary = "Không thể tạo tổng kết mối quan hệ server lúc này."
        # Write to file
        server_summary_path = os.path.join(self.data_dir, "server_relationships.txt")
        async with aiofiles.open(server_summary_path, mode="w", encoding="utf-8") as f:
            await f.write(
                "# server_relationships.txt\n# This file is auto-generated by the bot. Do not edit manually.\n\n"
            )
            await f.write(ai_summary)

    def _build_server_relationships_prompt(self, summary_data: dict) -> str:
        """Build prompt for AI to summarize all server relationships"""
        prompt = """Tổng hợp và phân tích các mối quan hệ trong server Discord dựa trên dữ liệu sau. Hãy chỉ sử dụng user_id để tránh nhầm lẫn tên. Trả lời bằng tiếng Việt, ngắn gọn, dễ hiểu, có thể chia thành các mục:

"""
        prompt += f"TỔNG NGƯỜI DÙNG: {summary_data['total_users']}\nTỔNG MỐI QUAN HỆ: {summary_data['total_relationships']}\nTỔNG TƯƠNG TÁC: {summary_data['total_interactions']}\n\n"
        for user in summary_data["users"]:
            prompt += f"- User ID: {user['user_id']}: {user['relationship_count']} mối quan hệ, {user['interaction_stats'].get('total_interactions', 0)} tương tác\n"
        prompt += "\nDỮ LIỆU CHI TIẾT:\n"
        for user in summary_data["users"]:
            prompt += f"\n=== User ID: {user['user_id']} ===\n"
            prompt += f"Tên thật: {user.get('real_name', '')}\n"
            prompt += f"Số mối quan hệ: {user['relationship_count']}\n"
            prompt += f"Tổng tương tác: {user['interaction_stats'].get('total_interactions', 0)}\n"
            if user["interaction_stats"].get("top_contacts"):
                prompt += "Liên lạc thường xuyên: "
                prompt += (
                    ", ".join(
                        [
                            f"User ID: {c['user_id']} ({c['interaction_count']})"
                            for c in user["interaction_stats"]["top_contacts"]
                        ]
                    )
                    + "\n"
                )
        prompt += "\nHãy phân tích, nhận xét tổng quan về các nhóm/tương tác nổi bật, network xã hội, và đưa ra nhận định về từng người nếu có đủ dữ liệu.\nChỉ dùng user_id, không dùng tên hiển thị."
        return prompt
