"""T1 active memory constants."""

TOKEN_THRESHOLD = 2000
TRIGGER_COOLDOWN_SECONDS = 60
IDLE_TRIGGER_MINUTES = 15
KEEP_RECENT_MESSAGES_AFTER_SUMMARY = 5
TOPIC_SHIFT_MIN_STABLE_TURNS = 3
TOPIC_SHIFT_MIN_CONFIDENCE = 0.7
RECENT_CATALOGS_WINDOW = 5
